# Vagrant.configure("2") do |config|
#     config.vm.box = "ubuntu/trusty64"
#     config.vm.box_url = "https://vagrantcloud.com/ubuntu/trusty64"
#     config.vm.box_version = "20190514.0.0"

#     # config.vm.provider "virtualbox" do |vb|
#     #     vb.memory = "1024"
#     #     vb.cpus = "1"
#     # end

#     # config.vm.hostname = "peacoverS"
#     # specify a dedicated IP on the eth1 interface

# end

Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/bionic64"
    # config.vm.box_url = "https://vagrantcloud.com/hashicorp/bionic64"
end
  